# files
samples/simple.conf			etc/btsync/samples
samples/user.conf			etc/btsync/samples
icons/256/btsync.png		usr/share/icons/hicolor/256x256/apps
icons/128/btsync.png		usr/share/icons/hicolor/128x128/apps
icons/96/btsync.png			usr/share/icons/hicolor/96x96/apps
icons/64/btsync.png			usr/share/icons/hicolor/64x64/apps
icons/48/btsync.png			usr/share/icons/hicolor/48x48/apps
icons/32/btsync.png			usr/share/icons/hicolor/32x32/apps
icons/16/btsync.png			usr/share/icons/hicolor/16x16/apps

