#!/bin/bash

if [ -z $1 ]; then
	echo 'USAGE: makebtsdebian <version>'
	exit 1;
fi

if ! which pbuilder-dist > /dev/null; then
	echo 'ERROR: No pbuilder-dist installed'
	exit 1
fi

VERSION=$1

#for release in squeeze wheezy sid; do
#	if [ -f btsync_${VERSION}~${release}.dsc ]; then
#		for destarch in i386 amd64; do
#			if ! pbuilder-dist ${release} ${destarch} build btsync_${VERSION}~${release}.dsc; then
#				exit 1
#			fi
#		done
#	else
#		echo No version ${VERSION} available for ${release}
#	fi
#done

if [ -f btsync_${VERSION}.dsc ]; then
	for destarch in i386 amd64; do
		if ! pbuilder-dist unstable ${destarch} build btsync_${VERSION}.dsc; then
			exit 1
		fi
	done
else
	echo No version ${VERSION} available for Debian unstable
fi
