#!/bin/bash

if [ -z $1 ]; then
	echo 'USAGE: makebinubuntu <version> [<PPA>]'
	exit 1;
fi

if ! which dput > /dev/null; then
	echo 'ERROR: No dput installed'
	exit 1
fi

VERSION=$1

if [ -z $2 ]; then
	PPA=ppa:tuxpoldo/btsync
else
	PPA=$2
fi

for release in lucid precise quantal raring saucy; do
	if [ -f btsync_${VERSION}~${release}_source.changes ]; then
		dput ${PPA} btsync_${VERSION}~${release}_source.changes
	else
		echo No version ${VERSION} available for ${release}
	fi
done
