#!/usr/bin/env python
# coding=utf-8
#
# Copyright 2014 Leo Moll
#
# Authors: Leo Moll and Contributors (see CREDITS)
#
# Thanks to Mark Johnson for btsyncindicator.py which gave me the
# last nudge needed to learn python and write my first linux gui
# application. Thank you!
#
# This file is part of btsync-gui. btsync-gui is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

import os
import sys
import argparse
import logging
import subprocess

sys.path.append('/usr/lib/btsync-gui')

from gi.repository import Gtk
from btsyncagent import *
from btsyncstatus import *


if __name__ == "__main__":
	parser = argparse.ArgumentParser()

	parser.add_argument('--log', choices=['CRITICAL','ERROR','WARNING','INFO','DEBUG'],
				default='WARNING',
				help="Set logging level")
	parser.add_argument('--host',
				default='auto',
				help="Hostname for the connection to BitTorrent Sync")
	parser.add_argument('--port', type=int,
				default=8888,
				help="Port number for the connection to BitTorrent Sync")

	parser.add_argument('--username',
				default=None,
				help="Optional user name for the connection to BitTorrent Sync")

	parser.add_argument('--password',
				default=None,
				help="Optional password for the connection to BitTorrent Sync")

	args = parser.parse_args()

	# initialize logger
	numeric_level = getattr(logging, args.log.upper(), None)
	if not isinstance(numeric_level, int):
		raise ValueError('Invalid log level: %s' % args.log)
	logging.basicConfig(level=numeric_level)
	fh = logging.FileHandler(filename=os.environ['HOME'] + '/.btsync/btsync-gui.log')
	ff = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
	fh.setFormatter(ff)
	logging.getLogger().addHandler(fh)
	logging.getLogger().setLevel(numeric_level)

	try:
		# initialize agent
		agent = BtSyncAgent(args)
	except Exception:
		logging.warning('Only one full btsync-gui can run at once.')
		exit(-1)

	try:
		agent.startup()
		# initialize indicator
		ind = BtSyncStatus()
		ind.startup(agent)
		# giro giro tondo....
		Gtk.main()
	except Exception:
		logging.error('This should never happen... ;-)')
	finally:
		# good night!
		ind.shutdown()
		agent.shutdown()
		logging.shutdown()
		exit(0)

