# files
btsync-gui					usr/bin
btsyncagent.py					usr/lib/btsync-gui
btsyncapi.py					usr/lib/btsync-gui
btsyncapp.glade					usr/lib/btsync-gui
btsyncapp.py					usr/lib/btsync-gui
btsyncstatus.glade				usr/lib/btsync-gui
btsyncstatus.py					usr/lib/btsync-gui
btsyncutils.py					usr/lib/btsync-gui
dialogs.glade					usr/lib/btsync-gui
dialogs.py					usr/lib/btsync-gui
trayindicator.py				usr/lib/btsync-gui

btsync-gui.desktop				usr/share/applications

icons/256x256/apps/btsync-gui.png		usr/share/icons/hicolor/256x256/apps
icons/128x128/apps/btsync-gui.png		usr/share/icons/hicolor/128x128/apps
icons/64x64/apps/btsync-gui.png			usr/share/icons/hicolor/64x64/apps
icons/48x48/apps/btsync-gui.png			usr/share/icons/hicolor/48x48/apps
icons/32x32/apps/btsync-gui.png			usr/share/icons/hicolor/32x32/apps
icons/16x16/apps/btsync-gui.png			usr/share/icons/hicolor/16x16/apps

icons/22x22/status/btsync-gui-disconnected.png	usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-connecting.png	usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-paused.png	usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-0.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-1.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-2.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-3.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-4.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-5.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-6.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-7.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-8.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-9.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-10.png		usr/share/icons/hicolor/22x22/status
icons/22x22/status/btsync-gui-11.png		usr/share/icons/hicolor/22x22/status

icons/36x36/status/btsync-gui-disconnected.png	usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-connecting.png	usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-paused.png	usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-0.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-1.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-2.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-3.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-4.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-5.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-6.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-7.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-8.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-9.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-10.png		usr/share/icons/hicolor/36x36/status
icons/36x36/status/btsync-gui-11.png		usr/share/icons/hicolor/36x36/status

